# Generated by Django 3.2.3 on 2022-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="Address"),
        ),
    ]
