# Generated by Django 3.2.3 on 2022-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20221026_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="staff"),
        ),
    ]
