# Generated by Django 3.2.3 on 2022-10-26 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number should exactly be in 10 digits",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
    ]
