name: GeoDjango CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install GIS system packages
      run: |
        sudo apt-get update
        sudo apt-get install binutils libproj-dev gdal-bin python3-gdal -y
        
    - name: Install App Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Linting with  flake8
      run: |
        pip install flake8 isort black
        flake8 --ignore=E501,F401 .
        
    - name: Running module Tests
      run: |      
        python manage.py test
