name: Django CI

on:
  push:
    branches: [ "authentication" ]
  pull_request:
    branches: [ "authentication" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install shapely geopy geopandas pyproj Shapely Fiona
        pip install psycopg2
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
